server:
  port: 8877
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application: 
    name: 'shopping-page-ms'
  datasource:
    username: pinyougou
    password: pinyougou
    url: 'jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai'
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
mybatis:
  type-aliases-package: com.online.shopping.pojo
  mapper-locations: 'classpath*:com/**/*Mapper.xml'

pagehelper:
  helper-dialect: mysql
  reasonable: true

 